# Generated by Django 2.2 on 2019-08-19 05:42

import apps.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.utils.FilenameChanger('cut'), verbose_name='이미지')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'verbose_name': '컷',
                'verbose_name_plural': '컷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='이름')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('cut', models.ManyToManyField(to='post.Cut', verbose_name='컷')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='post.Tag', verbose_name='태그')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Writer', verbose_name='작가')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트',
                'ordering': ['-created_at'],
            },
        ),
    ]
