# Generated by Django 2.2 on 2019-08-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cut',
            options={'ordering': ['priority'], 'verbose_name': '컷', 'verbose_name_plural': '컷'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='cut',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='cuts',
            field=models.ManyToManyField(blank=True, to='post.Cut', verbose_name='컷'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.Tag', verbose_name='태그'),
        ),
    ]
