# Generated by Django 2.2 on 2019-08-19 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190819_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1023, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
