# Generated by Django 2.2 on 2019-08-19 05:42

import apps.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='이름')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.FilenameChanger('writer/image'), verbose_name='이미지')),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호')),
                ('instagram', models.CharField(blank=True, max_length=1023, null=True, verbose_name='인스타그램')),
                ('facebook', models.CharField(blank=True, max_length=1023, null=True, verbose_name='페이스북')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='이름')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.FilenameChanger('profile/image'), verbose_name='이미지')),
                ('phone_num', models.CharField(blank=True, help_text='- 없이 숫자만 입력해주세요.', max_length=15, null=True, verbose_name='전화번호')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
                'ordering': ['name'],
            },
        ),
    ]
