# Generated by Django 2.2 on 2019-08-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(blank=True, help_text='- 없이 숫자만 입력해주세요.', max_length=15, null=True, unique=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='전화번호'),
        ),
    ]
