# Generated by Django 2.2 on 2019-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('content', models.TextField(verbose_name='내용')),
                ('code', models.CharField(blank=True, max_length=7, null=True, verbose_name='인증 코드')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '인증 코드')], default=1, verbose_name='타입')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': 'Email 내역',
                'verbose_name_plural': 'Email 내역',
                'ordering': ['-created_at'],
            },
        ),
    ]
