# Generated by Django 2.2 on 2019-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='성공 여부'),
        ),
    ]
