# Generated by Django 2.2 on 2019-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_emailhistory_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='인증 완료 여부'),
        ),
    ]
